// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SCNBioskoponline3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sCNBioskoponline3() {
    // Test name: SCN_Bioskop online_3
    // Step # | name | target | value
    // 1 | open | https://bioskoponline.com/ | 
    driver.get("https://bioskoponline.com/");
    // 2 | setWindowSize | 1050x708 | 
    driver.manage().window().setSize(new Dimension(1050, 708));
    // 3 | mouseOver | css=.w-36:nth-child(6) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".w-36:nth-child(6)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | css=.w-36:nth-child(6) | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | click | css=.w-36:nth-child(6) > .font-bold | 
    driver.findElement(By.cssSelector(".w-36:nth-child(6) > .font-bold")).click();
    // 6 | click | name=username | 
    driver.findElement(By.name("username")).click();
    // 7 | type | name=username | fikriirhm148@gmail.com
    driver.findElement(By.name("username")).sendKeys("fikriirhm148@gmail.com");
    // 8 | click | css=.bg-transparent | 
    driver.findElement(By.cssSelector(".bg-transparent")).click();
    // 9 | type | css=.bg-transparent | Nirmana148
    driver.findElement(By.cssSelector(".bg-transparent")).sendKeys("Nirmana148");
    // 10 | click | css=.desktop\3Atext-lg | 
    driver.findElement(By.cssSelector(".desktop\\3Atext-lg")).click();
  }
}
